# Generated by Django 4.2 on 2023-04-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('descricao', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
