# Generated by Django 4.2 on 2023-05-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contatos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='imagem',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
